databases:
        - name: moneta3
          databaseName: moneta3_production
          user: moneta3

services:
        - type: web
          name: moneta3
          env: ruby
          buildCommand: "./bin/render-build.sh"
          startCommand: "bundle exec puma -C config/puma.rb"
          envVars:
                  - key: DATABASE_URL
                    fromDatabase:
                            name: moneta3_production
                            property: connectionString
                  - key: RAILS_MASTER_KEY
                    sync: false
                            
